# Generated by Django 5.1.4 on 2024-12-15 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0002_organization_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, limit_choices_to={'org_type': 'org_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='queue_manager.organization'),
        ),
        migrations.AlterField(
            model_name='line',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='line',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='queue_manager.organization'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('aadhaar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='queue_manager.line')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('queue', 'user'), name='unique_registration')],
            },
        ),
    ]
